config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  
  post 'attends' => 'attends#create'
  
  delete 'attends/:id' => 'attends#destroy'
  
  post 'comments' => 'comments#create'
  
  get 'comments/:id' => 'comments#edit'
  
  
  delete 'comments/:id' => 'comments#destroy'
  
  resources :sessions
  resources :users
  resources :events
  

end

app/models/attend.rb
class Attend < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  has_many :attends, dependent: :destroy
  has_many :user_attends, through: :attends, source: :user
  
  has_many :comments, dependent: :destroy
  has_many :user_comments, through: :comments, source: :user
  
  
  validates :name, :date, :location, :state, presence: true
  validates :user_id, presence: true, on: :create
  
  private
  
  def self.filtered_events_by_state(state)
    events = Event.all
    instate_events = []
    outstate_events = []
    events.each do |event|
      if event.state == state 
        instate_events << event
      else
        outstate_events << event
      end
    end
    return {instate: instate_events, outstate: outstate_events }
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :events, dependent: :destroy
  has_many :attends, dependent: :destroy
  has_many :events_attend, through: :attends, source: :events
  
  has_many :comments, dependent: :destroy
  has_many :event_comments, through: :comments, source: :events

  has_secure_password
  EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i
  validates :first_name , :last_name, :location, :state, presence: true
  validates :email, presence: true, uniqueness: {case_sensitive: false} , format: {with: EMAIL_REGEX}
  validates :password, length: {minimum: 6}, on: :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
  
  def current_user
    User.find(session[:user_id]) if session[:user_id]
    rescue ActiveRecord::RecordNotFound
      reset_session
  end 
  helper_method :current_user
  
end

app/controllers/attends_controller.rb
class AttendsController < ApplicationController
    def create 
        Attend.create(user_id: current_user.id, event_id: params[:event_id])
        redirect_to events_url
    end
    
    def destroy
        attend = Attend.find(params[:id]).delete
        redirect_to events_url
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :set_comment, only: [:edit, :update, :destroy]
    def create
        Comment.create(content: params[:content], event_id: params[:event_id], user_id: current_user.id)
        redirect_to event_url(params[:event_id])
    end
    
    def destroy
        @comment.destroy
        redirect_to(:back)
        
    end
    
    private
    def set_comment
        @comment = Comment.find(params[:id])
    end 
    
    
    
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  
  def index
    @events = Event.filtered_events_by_state(current_user.state)
  end
  
  def create
    event = Event.create(event_params)
    puts event_params
    flash[:message] = event.errors.full_messages unless event.save
    redirect_to events_url
  end
  
  def show
  end
  
  def edit
  end
  
  def update
    @event.update(event_params)
    redirect_to events_url
  end
  
  def destroy
    @event.destroy
    redirect_to events_url
  end
  
  
  private
  
  def event_params
    params.require(:event).permit(:name, :date, :location, :state, :user_id)
  end
  
  def set_event
    @event = Event.find(params[:id])
  end
  
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    
  end
  
  def create
    user = User.find_by_email(params[:email])
    
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to events_url
    else 
      flash[:error] = 'Invalid Login'
      redirect_to new_session_url
      
    end
    
  end
  
  def destroy
    reset_session
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update]
  def create
    user = User.create(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to events_url
    else
      flash[:message] = user.errors.full_messages
      
      redirect_to new_session_url
    end
  end
  
  def edit
  end
  
  def update
    @user.update(user_params)
    redirect_to events_url
  end
  
  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :location, :state, :password, :password_confirmation)
  end
  
  def set_user
    @user = User.find(params[:id])
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attends_helper.rb
module AttendsHelper
    def find_id (attends, user_id)
        attends.find {|attend| attend.user_id == user_id}.id
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/states_helper.rb
module StatesHelper

def us_states
  [
    ['Alabama', 'AL'],
    ['Alaska', 'AK'],
    ['Arizona', 'AZ'],
    ['Arkansas', 'AR'],
    ['California', 'CA'],
    ['Colorado', 'CO'],
    ['Connecticut', 'CT'],
    ['Delaware', 'DE'],
    ['District of Columbia', 'DC'],
    ['Florida', 'FL'],
    ['Georgia', 'GA'],
    ['Hawaii', 'HI'],
    ['Idaho', 'ID'],
    ['Illinois', 'IL'],
    ['Indiana', 'IN'],
    ['Iowa', 'IA'],
    ['Kansas', 'KS'],
    ['Kentucky', 'KY'],
    ['Louisiana', 'LA'],
    ['Maine', 'ME'],
    ['Maryland', 'MD'],
    ['Massachusetts', 'MA'],
    ['Michigan', 'MI'],
    ['Minnesota', 'MN'],
    ['Mississippi', 'MS'],
    ['Missouri', 'MO'],
    ['Montana', 'MT'],
    ['Nebraska', 'NE'],
    ['Nevada', 'NV'],
    ['New Hampshire', 'NH'],
    ['New Jersey', 'NJ'],
    ['New Mexico', 'NM'],
    ['New York', 'NY'],
    ['North Carolina', 'NC'],
    ['North Dakota', 'ND'],
    ['Ohio', 'OH'],
    ['Oklahoma', 'OK'],
    ['Oregon', 'OR'],
    ['Pennsylvania', 'PA'],
    ['Puerto Rico', 'PR'],
    ['Rhode Island', 'RI'],
    ['South Carolina', 'SC'],
    ['South Dakota', 'SD'],
    ['Tennessee', 'TN'],
    ['Texas', 'TX'],
    ['Utah', 'UT'],
    ['Vermont', 'VT'],
    ['Virginia', 'VA'],
    ['Washington', 'WA'],
    ['West Virginia', 'WV'],
    ['Wisconsin', 'WI'],
    ['Wyoming', 'WY']
  ]
end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/edit.html.erb
<h2>Edit Event</h2>
<form action= "/events/<%= @event.id %>" method= 'post'>
    <input type='hidden' name='authenticity_token' value='<%= form_authenticity_token %>'>
    <input type ='hidden' name="_method" value='patch'>
    Name<%= text_field(:event, :name) %>
    Date: <%= date_field(:event, :date) %>
    Location: <%= text_field(:event, :location) %>
    State: <%= select(:event, :state, us_states) %>
   <input type ='submit' value ='Update Event'>
</form>
    

app/views/events/index.html.erb
<h2>Welcome <%= current_user.first_name %></h2>
<p><%= link_to "Edit User", edit_user_url(current_user.id) %></p>

<h4>Here are some of the events at your state:</h4>
<table class= "table table-striped">
        <tr>
            <th>Name</th>
            <th>Date</th>
            <th>Location</th>
            <th>Host</th>
            <th>Action/Status</th>
        </tr>
<% @events[:instate].each do |event| %>
        <tr>
            <td><%= link_to event.name, event_url(event.id) %></td>
            <td><%= event.date.to_s(:btf) %></td>
            <td><%= event.location %></td>
            <td><%=event.user.first_name %> </td>
        <% if event.user_id == current_user.id %>
            <td><%= link_to "Edit", edit_event_url(event.id) %> <%= link_to 'Delete', event, method: :delete,  data: { confirm: 'Are you sure?' } %></td>
        <% else %>
            <td>
            <% if event.user_attends.include?(current_user) %>
                <form action = "/attends/<%= find_id(event.attends, current_user.id) %>" method= 'post'>
                    <input type ='hidden' name='authenticity_token' value= '<%= form_authenticity_token %>'>
                    <input type ='hidden' name='_method' value='delete'>
                    Joined...<input type ='submit' value= 'Cancel'>                    
                </form>
            <% else %>
                <form action = '/attends' method= 'post'>
                    <input type ='hidden' name='authenticity_token' value= '<%= form_authenticity_token %>'>
                    <input type= 'hidden' name='event_id' value = <%= event.id %>>
                    <input type= 'submit' value= 'Join'>
                </form>
            <% end %>
            </td>
        <% end %>
<% end %>
</table>

<h4>Here are some events in other states:</h4>  
<table class =" table table-striped">
    <tr>
        <th>Name</th>
        <th>Date</th>
        <th>Location</th>
        <th>State</th>
        <th>Host</th>
        <th>Action/Status</th>
    </tr>
<% @events[:outstate].each do |event| %>
    <tr>
        <td><%= link_to event.name, event_url(event.id) %></td>
        <td><%= event.date.to_s(:btf) %></td>
        <td><%= event.location %></td>
        <td><%= event.state %></td>
        <td><%= event.user.first_name %> </td>
        <% if event.user_id == current_user.id %>
            <td><%= link_to "Edit", edit_event_url(event.id) %> <%= link_to 'Delete', event, method: :delete,  data: { confirm: 'Are you sure?' } %></td>
        <% else %>
            <td>
            <% if event.user_attends.include?(current_user) %>
                <form action = "/attends/<%= find_id(event.attends, current_user.id) %>" method= 'post'>
                    <input type ='hidden' name='authenticity_token' value= '<%= form_authenticity_token %>'>
                    <input type ='hidden' name='_method' value='delete'>
                    Joined...<input type ='submit' value= 'Cancel'>                    
                </form>
            <% else %>
                <form action = '/attends' method= 'post'>
                    <input type ='hidden' name='authenticity_token' value= '<%= form_authenticity_token %>'>
                    <input type= 'hidden' name='event_id' value = <%= event.id %>>
                    <input type= 'submit' value= 'Join'>
                </form>
            <% end %>
            </td>
        <% end %>
<% end %>
</table>

<h3>Add an Event?</h3>

<form action= '/events' method = 'post'>
    <input type='hidden' name='authenticity_token' value='<%= form_authenticity_token %>'>
    Event Name:<%= text_field(:event, :name) %>
    Date: <%= date_field(:event, :date) %>
    Location: <%= text_field(:event, :location) %>
    State: <%= select(:event, :state, us_states) %>
    <input type='hidden' name='event[user_id]' value = <%= current_user.id %>>
    <input type ='submit' value ='Add Event'>
</form>

app/views/events/show.html.erb
<h1><%= @event.name %></h1>
<h3>Host: <%= @event.user.first_name %> <%= @event.user.last_name %></h3>
<h3>Date: <%= @event.date.to_time.strftime('%B %e %Y') %></h3>
<h3>Location: <%= @event.location %>, <%= @event.state %> </h3>
<h3>People Attending: <%= @event.attends.count %></h3>

<table class="table table-striped">
    <tr>
        <th>Name</th>
        <th>Location</th>
        <th>State</th>
    </tr>

<% @event.attends.each do |attend| %>
    <tr>
        <td><%= attend.user.first_name %></td>
        <td><%= attend.user.location %></td>
        <td><%= attend.user.state %></td>
    </tr>
<% end %>
</table>

<h3>Discussion about the event:</h3>
<% @event.comments.each do |comment| %>
    <p><%= comment.user.first_name %> says: <%=comment.content %></p>
<% end %>

<form action= '/comments' method= 'post'>
    <input type='hidden' name='authenticity_token' value='<%= form_authenticity_token %>'>
    Add Comment:<input type='text' name='content'>
    <input type='hidden' name= 'event_id' value= <%= @event.id %>>
    <input type='submit' value='Submit Comment'>
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
<% if current_user %>
   <form action='/sessions/<%= current_user.id %>' method='post'>
      <input type='hidden' name='authenticity_token' value='<%= form_authenticity_token %>'>
      <input type='hidden' name='_method' value='delete'>
      <input type='submit' value='Log Out'>
    </form>
<% end %>
<% if current_user %>
  <% if !current_page?(:controller => :'events', :action => 'index') %>
    <%= link_to "Events Dashboard", events_url %>
  <% end %>
<% end %>

<%= yield %>


</body>
</html>

app/views/users/edit.html.erb
<h2>Edit Your Profile</h2>
<form action= "/users/<%= @user.id %>" method= 'post'>
    <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
    <input type ='hidden' name="_method" value='patch'>
    First Name:<%= text_field(:user, :first_name) %>
    Last Name:<%= text_field(:user, :last_name) %>
    Email: <%= email_field(:user, :email) %>
    Location: <%= text_field(:user, :location) %>
    State: <%= select(:user, :state, us_states) %>
    <input type= 'submit' value='Update Records'>
</form>